apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.web.service.name }}
  labels:
    release: {{ .Release.Name }}
    {{- toYaml .Values.web.service.labels | nindent 4 }}
spec:
  ports:
  - protocol: TCP
    port: {{ .Values.web.port }}
    nodePort: {{ .Values.web.service.nodePort }}
  - port: {{ .Values.web.sslPort }}
    nodePort: {{ .Values.web.service.sslNodePort }}
  type: NodePort
  selector:
    {{- toYaml .Values.web.serviceSelectorLabels | nindent 4 }}
